### ISSUE TITLE
this test show me that plugin does not work

### ISSUE THREAD

**Issue by Rombersoft** [brodybits/cordova-sqlite-test-app#3]
OPEN database: sample.db
SQLitePlugin.js:102 new transaction is waiting for open operation
SQLitePlugin.js:192 OPEN database: sample.db failed, aborting any pending transactions
SQLitePlugin.js:79 Could not open database

**Comment by brody2consult** [comment]
My apologies for the delay. In case this is still an issue please report which platform and post a copy of your workarea.

**Comment by Rombersoft** [comment]
I have changed to xamarin. Have a nice problem
